#!/bin/bash
echo ""
echo -e "\033[1;36m══════════════════════════════════════════════════\033[0m"
echo -e "  \033[1;33m💼 WORK EXPERIENCE\033[0m"
echo -e "\033[1;36m══════════════════════════════════════════════════\033[0m"
echo ""
echo -e "\033[1;37m[2022 - Present]  Senior DevOps Engineer\033[0m"
echo -e "\033[32m                  TechCorp Solutions, Mumbai\033[0m"
echo "  • Reduced deployment time 70% with GitOps pipeline"
echo "  • Managed 50+ microservices on Kubernetes (EKS)"
echo "  • Built self-healing infra with auto-scaling groups"
echo "  • Saved \$40K/year through cloud cost optimization"
echo ""
echo -e "\033[1;37m[2021 - 2022]     DevOps Engineer\033[0m"
echo -e "\033[32m                  StartupXYZ, Pune\033[0m"
echo "  • Containerized 20+ legacy apps with Docker"
echo "  • Set up Prometheus + Grafana monitoring"
echo "  • Automated infra with Terraform"
echo "  • Zero-downtime blue-green deployments"
echo ""
echo -e "\033[1;37m[2020 - 2021]     Cloud Intern\033[0m"
echo -e "\033[32m                  CloudBase India, Bangalore\033[0m"
echo "  • AWS infrastructure management"
echo "  • Bash & Python automation scripts"
echo ""
