#!/bin/bash
echo ""
echo -e "\033[1;36m══════════════════════════════════════════════════\033[0m"
echo -e "  \033[1;33m💼 WORK EXPERIENCE\033[0m"
echo -e "\033[1;36m══════════════════════════════════════════════════\033[0m"
echo ""
echo -e "\033[1;37m[2025 - Present]  DevOps Engineer\033[0m"
echo -e "\033[32m                  CloudDrove, Canada\033[0m"
echo "  • Reduced deployment time 70% with GitOps pipeline"
echo "  • Managed 50+ microservices on Kubernetes (EKS)"
echo "  • Built self-healing infra with auto-scaling groups"
echo "  • Saved \$40K/year through cloud cost optimization"
echo ""
echo -e "\033[1;37m[2024 - 2024]     SDE Intern\033[0m"
echo -e "\033[32m                  BlueStock Fintech, Pune\033[0m"
echo "  • Develop, test, and deploy new features while resolving existing bugs."
echo "  • Participated in daily stand-ups, wrote reusable React components, and ensured mobile responsiveness."
echo "  • Produced and deployed dynamic frontend modules in a fast-paced fintech environment, ensuring platform stability."
echo "  • Worked on React and Node.js, contributing to the development of a high-traffic financial application."
echo ""
